---
mdd_data:
  mdd:openconfig:
    openconfig-network-instance:network-instances:
      openconfig-network-instance:network-instance:
      - openconfig-network-instance:name: default
        openconfig-network-instance:config:
          openconfig-network-instance:name: default
          openconfig-network-instance:type: DEFAULT_INSTANCE
          openconfig-network-instance:enabled: 'true'
        openconfig-network-instance:protocols:
          openconfig-network-instance:protocol:
          - openconfig-network-instance:identifier: STATIC
            openconfig-network-instance:name: DEFAULT
            openconfig-network-instance:config:
              openconfig-network-instance:identifier: STATIC
              openconfig-network-instance:name: DEFAULT
            openconfig-network-instance:static-routes:
              openconfig-network-instance:static: []
        openconfig-network-instance:interfaces:
          openconfig-network-instance:interface: []
        openconfig-network-instance:vlans:
          openconfig-network-instance:vlan: []
      - openconfig-network-instance:name: Mgmt-intf
        openconfig-network-instance:config:
          openconfig-network-instance:name: Mgmt-intf
          openconfig-network-instance:type: L3VRF
          openconfig-network-instance:enabled: 'true'
          openconfig-network-instance:enabled-address-families:
          - openconfig-types:IPV4
          - openconfig-types:IPV6
        openconfig-network-instance:protocols:
          openconfig-network-instance:protocol: []
        openconfig-network-instance:interfaces:
          openconfig-network-instance:interface: []
mdd_tags:
- WAN_router
