---
mdd_data:
  mdd:openconfig:
    openconfig-interfaces:interfaces:
      openconfig-interfaces:interface:
      - openconfig-interfaces:name: GigabitEthernet0/0
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet0/0
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
            openconfig-if-ip:ipv4:
              openconfig-if-ip:addresses:
                openconfig-if-ip:address: []
              openconfig-if-ip:config:
                openconfig-if-ip:dhcp-client: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet0/1
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet0/1
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet0/2
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet0/2
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet0/3
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet0/3
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet1/0
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet1/0
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet1/1
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet1/1
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet1/2
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet1/2
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet1/3
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet1/3
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet2/0
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet2/0
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet2/1
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet2/1
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet2/2
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet2/2
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet2/3
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet2/3
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet3/0
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet3/0
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet3/1
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet3/1
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet3/2
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet3/2
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
      - openconfig-interfaces:name: GigabitEthernet3/3
        openconfig-interfaces:config:
          openconfig-interfaces:name: GigabitEthernet3/3
          openconfig-interfaces:type: ethernetCsmacd
          openconfig-interfaces:enabled: true
        openconfig-interfaces:subinterfaces:
          openconfig-interfaces:subinterface:
          - openconfig-interfaces:index: 0
            openconfig-interfaces:config:
              openconfig-interfaces:index: 0
              openconfig-interfaces:enabled: true
        openconfig-if-ethernet:ethernet:
          openconfig-if-ethernet:config:
            openconfig-if-ethernet:auto-negotiate: true
mdd_tags:
- switch
