- name: Dump NSO Config Data
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    current_dir: "{{ lookup('env','PWD') }}"
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: get_config

    - name: Create the device_config_data directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'PWD') }}/device_config_data"
        state: directory

    - set_fact:
        nso_device_config: "{ 'mdd_data': { 'config': {{ nso_device_config['config'] }} } }"

    - copy:
        content: "{{ nso_device_config | ciscops.mdd.to_even_nicer_yaml }}"
        dest: "{{ current_dir }}/device_config_data/{{ inventory_hostname }}.yml"
